Fix _shift_positions for cancelled reservations
Currently when adding a new application to an apartment that already has cancelled
reservations the _shift_positions fails with the following error:

    RuntimeError: This function cannot be used for adding a
    reservation when the apartment has reservations without a queue_position.

This was caused because cancelled reservations have queue_position == None.

Fix the issue by filtering out the cancelled reservations.